In [10]:
# ! pip install numpy

In [11]:
# ! pip install pandas

In [12]:
# ! pip install matplotlib
# ! pip install seaborn, scipy, sklearn

In [13]:
import numpy as np

np_array = np.array([1,2,3,4,5])
print(np_array, type(np_array))

[1 2 3 4 5] <class 'numpy.ndarray'>


3D array

In [14]:
try:
    data = np.loadtxt('titanic-data.csv',delimeter=',')
    print(data)
except:
    print('Error')

Error


In [17]:
A = np.array([[1,2,3],[1,2,3]])
B = np.array([[1,2,3],[1,2,3]])

print(A + B)
print(A - B)
print(A * B)
print(A / B)


[[2 4 6]
 [2 4 6]]
[[0 0 0]
 [0 0 0]]
[[1 4 9]
 [1 4 9]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
print(np.dot(A,B))

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [19]:
'''Dot matrix multiplication is not possible by A*B
    You must use np.dot() function.'''
A = np.array([[1,2,3],[1,2,3],[1,2,3]])
B = np.array([[1,2,3],[1,2,3],[1,2,3]])

print(np.dot(A,B))

[[ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]]


In [20]:
np.random.random((2,3))

array([[0.15817299, 0.72519685, 0.18717125],
       [0.53991565, 0.40564268, 0.30458678]])

In [21]:
np.zeros([2,3,5])

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [22]:
np.random.random([20])

array([0.94295775, 0.1816794 , 0.47504225, 0.83001144, 0.03497968,
       0.67718897, 0.34585698, 0.64629874, 0.91422573, 0.46056641,
       0.60866947, 0.56815079, 0.25479424, 0.40438688, 0.77473487,
       0.64343   , 0.51269702, 0.34253025, 0.63758299, 0.38358672])

In [23]:
np.random.randint(1,10,20)

array([3, 8, 2, 4, 1, 5, 3, 7, 4, 1, 2, 8, 8, 8, 6, 1, 2, 7, 2, 5])